import os,hashlib,json
root='/home/claude/charlita'
files=[]
for d,_,fs in os.walk(root):
    for f in fs:
        p=os.path.relpath(os.path.join(d,f),root)
        if p in ('sw.js',) or p.startswith('.') or p.endswith('.md') or p.startswith('tests') or p.startswith('tools') or p.startswith('README'): continue
        files.append(p)
files.sort()
h=hashlib.sha1()
for f in files: h.update(open(os.path.join(root,f),'rb').read())
ver=h.hexdigest()[:10]
urls=['./']+files
sw=f"""// Generated by build/make_sw.py — do not edit by hand.
const CACHE = 'charlita-{ver}';
const PRECACHE = {json.dumps(urls)};
self.addEventListener('install', e => {{
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(PRECACHE)));
}});
self.addEventListener('activate', e => {{
  e.waitUntil(caches.keys().then(ks => Promise.all(ks.filter(k => k.startsWith('charlita-') && k !== CACHE).map(k => caches.delete(k)))).then(() => self.clients.claim()));
}});
self.addEventListener('message', e => {{ if (e.data === 'skip') self.skipWaiting(); }});
self.addEventListener('fetch', e => {{
  const req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== location.origin) return;
  e.respondWith(caches.match(req, {{ ignoreSearch: true }}).then(hit => hit || fetch(req).then(res => {{
    if (res.ok) {{ const copy = res.clone(); caches.open(CACHE).then(c => c.put(req, copy)); }}
    return res;
  }}).catch(() => req.mode === 'navigate' ? caches.match('./') : Response.error())));
}});
"""
open(os.path.join(root,'sw.js'),'w').write(sw)
print(ver,len(urls))
