// Generated by build/make_sw.py — do not edit by hand.
const CACHE = 'charlita-ca7b2b84a8';
const PRECACHE = ["./", "css/app.css", "data/detective.json", "data/verbs.json", "data/words.json", "fonts/fraunces-latin-wght-italic.woff2", "fonts/fraunces-latin-wght-normal.woff2", "fonts/nunito-latin-wght-normal.woff2", "icons/apple-touch-icon.png", "icons/icon-192.png", "icons/icon-512.png", "icons/icon-maskable-512.png", "index.html", "js/animals.js", "js/app.js", "js/cards.js", "js/checker.js", "js/data.js", "js/db.js", "js/store.js", "manifest.webmanifest"];
self.addEventListener('install', e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(PRECACHE)));
});
self.addEventListener('activate', e => {
  e.waitUntil(caches.keys().then(ks => Promise.all(ks.filter(k => k.startsWith('charlita-') && k !== CACHE).map(k => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener('message', e => { if (e.data === 'skip') self.skipWaiting(); });
self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== location.origin) return;
  e.respondWith(caches.match(req, { ignoreSearch: true }).then(hit => hit || fetch(req).then(res => {
    if (res.ok) { const copy = res.clone(); caches.open(CACHE).then(c => c.put(req, copy)); }
    return res;
  }).catch(() => req.mode === 'navigate' ? caches.match('./') : Response.error())));
});
